name: Release the wheels to Github Release
# The wheel is deployed to Github release as draft when the git tag with "rc" is pushed
# Otherwise, the wheel in only uploaded as artifact and the release is not created.

on:
 push:
    tags:
        - 'v*.*.*' # This will trigger the workflow on version tags like v1.0.0, v2.1.3, etc.

jobs:
  build_wheels:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build 

      - name: Build package
        run: python -m build --wheel

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-3.13
          path: dist/

  test_artifacts:
    runs-on: windows-latest
    needs: build_wheels

    steps:
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
            python-version: "3.9"

      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-3.13
          path: dist

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install --find-links ./dist pyDIFI

      - name: Test installation
        shell: bash
        run: |
          python -c "import DIFI as difi; print(difi.__version__)"


  release:
    name: Create GitHub Release
    # Draft if 'rc' (release candidate) in tag e.g. v1.0.0rc0.
    # The action performed by GITHUB_TOKEN will prevent the event triggered from other workflows.
    # To release the package to pypi, the release will be triggered manually by the user after the release is created. This is to prevent accidental releases to pypi.
    if: ${{ contains( github.ref_name, 'rc' ) }}
    runs-on: ubuntu-latest
    needs: [build_wheels, test_artifacts]

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: wheels-3.13
          path: dist

      - name: Upload wheels to Github Release
        uses: softprops/action-gh-release@v1

        with:
          files: dist/*.whl
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}